version: '3'

services:
  auth:
    container_name: auth
    build: ./auth/
    command: python3 manage.py runserver 0.0.0.0:5001
    expose:
      - 5001
    ports:
      - 5001:5001
    restart: always

  order-service:
    container_name: order-service
    depends_on:
      - "order_pg_db"
    build: ./order/
    ports:
      - 3000:3000
    restart: always
    environment:
      DATABASE_NAME: order_pg_db
      DATABASE_HOST_DIRECT: order_pg_db
      HOSTNAME: order_pg_db
      AUTH_SERVICE_BASE_URL: http://auth:5001

  order_pg_db:
    container_name: order_pg_db
    image: postgres:13.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: order_pg_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - order_pg_db:/var/lib/postgresql/data
  
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    expose:
      - "2181"
    restart: always
    container_name: zookeeper

  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
      - "9092:9092"
    expose:
      - "9092"
    environment:
      KAFKA_CREATE_TOPICS: "domain_orderservice_schedule_approved_0:2:1"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://broker:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
    restart: always
    container_name: broker
  
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka"

volumes:
  order_pg_db:
